export const INCREMENT_NUMBER = 'INCREMENT_NUMBER'
export type INCREMENT_NUMBER = typeof INCREMENT_NUMBER

export const DECREMENT_NUMBER = 'DECREMENT_NUMBER'
export type DECREMENT_NUMBER = typeof DECREMENT_NUMBER

export const ASYNC_INCREMENT_NUMBER = 'ASYNC_INCREMENT_NUMBER'
export type ASYNC_INCREMENT_NUMBER = typeof ASYNC_INCREMENT_NUMBER
